### ISSUE TITLE
Why are there no CAD files?

### ISSUE THREAD

**Issue by luzpaz** [GliaX/Otoscope#4] opened 2019-08-16 11:20 UTC
I'm part of the FreeCAD community outreach team. There are a lot of volunteers on the forum that could be willing to help in this very cool endeavor. Feel free to post on our [Forums](https://forum.freecadweb.org/) to showcase your work or ask for help. 

Examples:  
* [3D printed canine hind limb](https://forum.freecadweb.org/viewtopic.php?t=26901)
* [Anyone interested in donating their time to make a clubfoot brace?](https://forum.freecadweb.org/viewtopic.php?t=27168)  
* [Open Source Ecology](https://wiki.opensourceecology.org/wiki/FreeCAD_101) onboards their community with FreeCAD  
etc...

**Comment by tareko** [comment] 2019-08-16 11:27
Thank you so much @luzpaz ! I'll look and post in the next day or two.
Our experience is such a testament to the need for FreeCAD, and why we base our work on FreeCAD and OpenSCAD as well. Thank you!

**Comment by eddriesen** [comment] 2019-08-18 18:30
I'm creating the files as we speak. Please do mind that freecad is new to me. So bare with me. 
 
Things i'm figuring out atm.;
- part / body / project structure
- ok to use assembly2 module (prime time?/ Getting an error on 0.18.3)
- seperate proj file for each component vs project file with multiple parts or bodies vs seperate files and assembly2 project file
- any topdown / associativity possible?

**Comment by luzpaz** [comment] 2019-08-18 23:17
No, Assembly2 is deprecated. Better to use Assembly2+ or Assembly3.  
Please open a thread on the FreeCAD forums to discuss with the community. Thanks!

**Comment by tareko** [comment] 2019-08-19 00:04
Thanks for the advice @luzpaz . Will open the thread tonight and post here.

**Comment by tareko** [comment] 2019-08-19 00:31
[Posted to the FreeCAD forums](https://forum.freecadweb.org/viewtopic.php?f=31&t=38643)

**Comment by rewolff** [comment] 2019-08-26 07:25
I read you wanted help in converting to openscad (or freecad which I don't know). 
I have started a bit, but it is much more difficult than expected. For example, The "button_block" looks as if it is the difference between three rectangular blocks (with critical parameters 18.45, 1.398, 12.747 and 13.000) and a sphere. But it turns out that sphere is not a sphere. So.... To help me: What kinds of shapes are involved in an object like the button_block ???

**Comment by tareko** [comment] 2019-08-26 07:49
Hi @rewolff! Just a quick note that there seems to be an active effort to do this in FreeCAD at the moment, which I think is more fit for purpose. You are welcome to continue in OpenSCAD, but you may feel this work is duplicating the work of others.

Regarding your specific query, I have poked @Frankie-E4Rdesigns about this to answer you more specifically. I don't think your replica is obliged to be 1:1, though obviously the pieces will have to fit together in the end.

Thank you again!

tarek : )

**Comment by Frankie-E4Rdesigns** [comment] 2019-08-28 22:33
Specula Holder, Handle cover, button lock, neck part, button block, and handle coupler all look great!

**Comment by tareko** [comment] 2019-08-30 09:27
OK, I figure instead I'm going to get rid of the PRs above and keep a list of TODO parts. This is a duplicate of the FreeCAD thread's list.. I'll keep it on the [first post I made](https://github.com/GliaX/Otoscope/issues/4#issuecomment-521977767).

**Comment by 0penBrain** [comment] 2019-08-30 12:35
@tareko : regarding both lens holders, as it can be some critical parts, I think it is necessary that we can get a 3D model or mechanical drawing of the lens itself (or eventually some optical/mathematical description of it). May you provide that ?

**Comment by Frankie-E4Rdesigns** [comment] 2019-08-30 12:45
Good idea on the lens schematics, will post something on that soon. 
Different 3x magnification lenses will have slightly different dimensions, but I will post about the one I use.

**Comment by mef51** [comment] 2023-02-14 23:44
PR #19 adds freecad files for
* inner_head
* outer_head
* lens_holder_bottom

**Closed** 2023-04-06 20:04 UTC
Labels: help wanted
